# Generated by Django 4.2.6 on 2024-01-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
