# Generated by Django 4.2.6 on 2024-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
