# Generated by Django 4.2.6 on 2024-01-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_number',
            new_name='room_name',
        ),
    ]
